///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetTaskModelSmsTask {
/*
{
  "task_id": 4,
  "to_number": "+94773853240",
  "message": "sdsdsd",
  "createdAt": "2023-01-08T14:14:29.000Z",
  "updatedAt": null
} 
*/

  int? taskId;
  String? toNumber;
  String? message;
  String? createdAt;
  String? updatedAt;

  GetTaskModelSmsTask({
    this.taskId,
    this.toNumber,
    this.message,
    this.createdAt,
    this.updatedAt,
  });
  GetTaskModelSmsTask.fromJson(Map<String, dynamic> json) {
    taskId = json['task_id']?.toInt();
    toNumber = json['to_number']?.toString();
    message = json['message']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['task_id'] = taskId;
    data['to_number'] = toNumber;
    data['message'] = message;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class GetTaskModel {
/*
{
  "id": 10,
  "task_id": 4,
  "user_id": 13,
  "sms_sent": 0,
  "createdAt": "2023-01-13T14:57:08.000Z",
  "updatedAt": null,
  "sms_task": {
    "task_id": 4,
    "to_number": "+94773853240",
    "message": "sdsdsd",
    "createdAt": "2023-01-08T14:14:29.000Z",
    "updatedAt": null
  }
} 
*/

  int? id;
  int? taskId;
  int? userId;
  int? smsSent;
  String? createdAt;
  String? updatedAt;
  GetTaskModelSmsTask? smsTask;

  GetTaskModel({
    this.id,
    this.taskId,
    this.userId,
    this.smsSent,
    this.createdAt,
    this.updatedAt,
    this.smsTask,
  });
  GetTaskModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    taskId = json['task_id']?.toInt();
    userId = json['user_id']?.toInt();
    smsSent = json['sms_sent']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    smsTask = (json['sms_task'] != null) ? GetTaskModelSmsTask.fromJson(json['sms_task']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['task_id'] = taskId;
    data['user_id'] = userId;
    data['sms_sent'] = smsSent;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    if (smsTask != null) {
      data['sms_task'] = smsTask!.toJson();
    }
    return data;
  }
}
