///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ModelLogin {
/*
{
  "id": 2,
  "username": "dan",
  "email": "dan.malshan@gmail.com",
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjczMTYwMzg3LCJleHAiOjE2NzMyNDY3ODd9.VVNjZPfWhM6Az0_-79S_C33d47Zr6xeeBa_Db0-efE0"
} 
*/

  int? id;
  String? username;
  String? email;
  String? accessToken;

  ModelLogin({
    this.id,
    this.username,
    this.email,
    this.accessToken,
  });
  ModelLogin.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    username = json['username']?.toString();
    email = json['email']?.toString();
    accessToken = json['accessToken']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['username'] = username;
    data['email'] = email;
    data['accessToken'] = accessToken;
    return data;
  }
}

ModelLogin? usr;
